spring.application.name=uberApplication

#DB configuration
spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/postgres}
spring.datasource.username=${DATABASE_USERNAME:postgres}
spring.datasource.password=${DATABASE_PASSWORD:nilayjain@j30}
#spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.hibernate.ddl-auto=${DDL_AUTO:update}
spring.jpa.show-sql=${SHOW_SQL:true}
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.defer-datasource-initialization=true

spring.sql.init.mode=${SQL_INIT_MODE:never}
spring.sql.init.data.locations=classpath:data.sql
#security configs
jwt.secretKey=${JWT_SECRET:ads9f6askj3h4k1hf86asdfiahkjh34a789s6df89ayshkjh3jkh786adsf78ay}

#smtp config
spring.mail.username=${MAIL_USERNAME:fitnessprojectnnnp25@gmail.com}
spring.mail.password=${MAIL_PASSWORD:nlug crej zjuc vbdj}
spring.mail.host=${MAIL_HOST:smtp.gmail.com}
spring.mail.port=${MAIL_PORT:587}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

server.port=${PORT:8081}
